name: Frontend PR

on:
  pull_request:
    paths:
      - 'devcloud-ui/**'
      - '!**.md'
  workflow_dispatch:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devcloud-ui

    steps:
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: cache .next
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install
        # remove --legacy-peer-deps as soon as next-auth supports Next.js 13 as peer dependency
        run: npm install --legacy-peer-deps

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint
